// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace SpeechFreeRadio
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "SpeechFreeRadio";
        public const string Version     = "1.0.3";
        public const string Title       = "Speech Free Radio";
        public const string Description = "Disable all talking on the in-game radio";
    }
}
